version: "3"

services:
  content-ai-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
      - GITHUB_PROVIDER_CLIENT_ID=${GITHUB_PROVIDER_CLIENT_ID}
      - GITHUB_PROVIDER_CLIENT_SECRET=${GITHUB_PROVIDER_CLIENT_SECRET}
      - GOOGLE_PROVIDER_CLIENT_ID=${GOOGLE_PROVIDER_CLIENT_ID}
      - GOOGLE_PROVIDER_CLIENT_SECRET=${GOOGLE_PROVIDER_CLIENT_SECRET}
      - BASE_URL=${BASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
