version: "3"

services:
  content-db:
    image: postgres:15
    container_name: content-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
      
  content-ai-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: content-ai-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
      - GITHUB_PROVIDER_CLIENT_ID=${GITHUB_PROVIDER_CLIENT_ID}
      - GITHUB_PROVIDER_CLIENT_SECRET=${GITHUB_PROVIDER_CLIENT_SECRET}
      - GOOGLE_PROVIDER_CLIENT_ID=${GOOGLE_PROVIDER_CLIENT_ID}
      - GOOGLE_PROVIDER_CLIENT_SECRET=${GOOGLE_PROVIDER_CLIENT_SECRET}
      - BASE_URL=${BASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    depends_on:
      - content-db

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
